[package]
name = "lumoscoin-second-proxy"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = "0.18.0"
solana-program = "1.7.14"
lumoscoin-logic = { path = "../../../lumoscoin-logic/programs/lumoscoin-logic" }

[features]
no-entrypoint = []

