[package]
name = "lumoscoin-first-proxy"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = "0.18.0"
solana-program = "1.7.14"
lumoscoin-second-proxy = { path = "../../../lumoscoin-second-proxy/programs/lumoscoin-second-proxy" }

[features]
no-entrypoint = []

